### PR TITLE
Fix blurhash zero width resizing bug

### PR DESCRIPTION
**Pull request by reekitconcept**
Under some circumstances the ResizeObserver is called on a zero offset image, which would cause the height to be reset and the blurhash disappear.

This might be a ResizeObserver bug in newer Chrome, or subject of a race condition. Precise reason unconfirmed.

### CODE REVIEW

**Comment by davisagli** [comment]
@reekitconcept @sneridagh Updating `@plone/scripts` should fix the build errors.

**Comment by reekitconcept** [comment]
@davisagli tried updating `@plone/scripts` to `1.2.2`, but the problem remains the same after the update.

**Comment by reekitconcept** [comment]
Hold the merge... another fix is coming.

**Comment by reekitconcept** [comment]
Ready to merge now. - A major reason was that the fast-blurhash file, that gets embedded into the page and loads the blurhashes before even React gets loaded, was not updated with the newest fixes.

**Comment by iFlameing** [comment]
@sneridagh can you please review this?

**Review by sneridagh — APPROVED** [review]

**Comment by sneridagh** [comment]
@iFlameing sorry

**Comment by sneridagh** [comment]
https://github.com/kitconcept/volto-blocks/releases/tag/12.3.7

**Pull request merged**
